# Render.com deployment configuration

# Build Command:
pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate

# Start Command:
gunicorn piticas_distribuicao.wsgi:application

# Environment Variables:
DEBUG=False
SECRET_KEY=your-secret-key-here-change-this
ALLOWED_HOSTS=*.onrender.com
PYTHON_VERSION=3.13.2

# Database:
# Render provides free PostgreSQL database
# DATABASE_URL will be automatically set
