# Generated by Django 5.2.5 on 2025-08-09 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('consultores', models.ManyToManyField(blank=True, to='distribuicao.consultor', verbose_name='Consultores')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PackGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pack')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuicao.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Pack de Grade',
                'verbose_name_plural': 'Packs de Grade',
                'ordering': ['grade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuicao.grade', verbose_name='Grade')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuicao.licenca', verbose_name='Licença')),
                ('pack_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuicao.packgrade', verbose_name='Pack de Grade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemPackGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('pack_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='distribuicao.packgrade', verbose_name='Pack de Grade')),
            ],
            options={
                'verbose_name': 'Item do Pack de Grade',
                'verbose_name_plural': 'Itens do Pack de Grade',
                'ordering': ['pack_grade', 'tamanho'],
                'unique_together': {('pack_grade', 'tamanho')},
            },
        ),
        migrations.CreateModel(
            name='ListaDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('quantidade_consultor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade para Consultor')),
                ('quantidade_loja', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade para Loja')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuicao.loja', verbose_name='Loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuicao.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lista de Distribuição',
                'verbose_name_plural': 'Listas de Distribuição',
                'ordering': ['-ano', '-mes', 'loja__codigo', 'produto__codigo'],
                'unique_together': {('mes', 'ano', 'loja', 'produto')},
            },
        ),
    ]
