# Generated by Django 5.2.5 on 2025-08-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='grade',
        ),
    ]
